language: go

addons:
  artifacts:
    working_dir: $GOPATH/bin
    debug: true

go:
  - '1.10'

install:
  - echo $PWD
  - ls -lah
  - curl https://glide.sh/get | sh
  - glide install
  - go install github.com/DigitalBitsOrg/go/services/bifrost
  - chmod +x $GOPATH/bin/bifrost
  - ls -lah $GOPATH/bin

matrix:
  fast_finish: true

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh 2>&1
  on:
    branch: OS-15