language: go
sudo: required
addons:
  artifacts:
    paths:
      - $GOPATH/bin/bifrost
    debug: true

go:
  - '1.10'

install:
  - mkdir $GOPATH/tmp
  - cp -Rf ./* $GOPATH/tmp && rm -Rf $GOPATH/src/DigitalBitsOrg
  - mkdir -p $GOPATH/src/github.com/digitalbitsorg/go
  - cp -Rf $GOPATH/tmp/* $GOPATH/src/github.com/digitalbitsorg/go && rm -Rf $GOPATH/tmp
  - cd $GOPATH/src/github.com/digitalbitsorg/go
  - curl https://glide.sh/get | sh
  - glide install

script:
  - go install github.com/digitalbitsorg/go/services/bifrost
  - chmod +x $GOPATH/bin/bifrost
  - mkdir $GOPATH/bifrost
  - cp $GOPATH/bin/bifrost $GOPATH/bifrost/bifrost

matrix:
  fast_finish: true

before_deploy:
  - pyenv global 2.7
  - pip install cloudsmith-cli

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh 2>&1
  on:
    branch: OS-15